### ISSUE TITLE
makeappx.exe version is too old

### ISSUE THREAD

**Issue by 0x504B0304** [Wapitiii/WSAppBak#2]
I met a error while the progrom calling makeappx.exe. I found it's version is too old to pack windowsapp today. So I downloaded a new version by install Windows SDK. Then everything work well.

**Comment by Wapitiii** [comment]
Yeah, i know if you want you can make a pull request and add it. Or i'll do that when i have the time.

**Comment by berkayfeci** [comment]
Hey i updated the files and created a pull request.

**Comment by Wapitiii** [comment]
resolved in #3
